version: '3.5'
networks:
  sdir:
    external: true

services:
  identityserver:
    container_name: idp
    restart: unless-stopped
    image: ${DOCKER_REGISTRY-}identityserver
    networks:
      sdir:
    environment:
      TZ: Europe/Oslo
    hostname: identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
